http:
  listener:
    host: "0.0.0.0"
    port: "9085"
  requester:
    travelOnTip:
      host: "localhost"
      port: "9083"
      routesPath: "/travelOnTip/routes"
      schedulesPath: "/travelOnTip/schedules"
    fastGo:
      host: "localhost"
      port: "9084"
      routesPath: "/fastGo/routes"
      schedulesPath: "/fastGo/schedules"